import type { LegalDocument, LegalDocumentCategory, ReportType } from "../types/legal-ai.types";

export const CATEGORY_LABELS: Record<LegalDocumentCategory, string> = {
  ALL: "Tất cả văn bản & biểu mẫu",
  LAW: "Luật (Quốc hội)",
  DECREE: "Nghị định (Chính phủ)",
  CIRCULAR: "Thông tư (Bộ ngành)",
  LOCAL: "Văn bản địa phương (Kiên Giang)",
  TEMPLATE: "Biểu mẫu chuẩn (BQL)",
};

export const STATUS_META = {
  EFFECTIVE: { label: "Còn hiệu lực", badge: "bg-emerald-50 text-emerald-700 border-emerald-200" },
  EXPIRED: { label: "Hết hiệu lực", badge: "bg-slate-100 text-slate-500 border-slate-200" },
  PARTIAL: { label: "Hết hiệu lực một phần", badge: "bg-amber-50 text-amber-700 border-amber-200" },
};

export const REPORT_TYPE_OPTIONS: { value: ReportType; label: string; desc: string }[] = [
  {
    value: "WEEKLY",
    label: "Báo cáo tiến độ tuần của Ban",
    desc: "Tổng hợp tiến độ M2, giải ngân tuần M4, các điểm nóng GPMB M6",
  },
  {
    value: "MONTHLY",
    label: "Báo cáo công tác quản lý dự án tháng",
    desc: "Báo cáo toàn diện định kỳ gửi UBND TP Hà Tiên & Sở Xây dựng",
  },
  {
    value: "GPMB_TOPIC",
    label: "Báo cáo chuyên đề Bồi thường & GPMB",
    desc: "Phân tích chi tiết 16 bước, các hộ chưa bàn giao, vướng mắc pháp lý",
  },
  {
    value: "DISBURSEMENT_TOPIC",
    label: "Báo cáo tình hình giải ngân vốn đầu tư công",
    desc: "Số liệu kế hoạch vốn, đối chiếu hạn mức KBNN và hợp đồng nhà thầu",
  },
  {
    value: "ANNUAL",
    label: "Báo cáo tổng kết công tác năm",
    desc: "Đánh giá toàn diện các chỉ tiêu năm, công trình hoàn thành, bảo hành",
  },
];

export const INITIAL_DOCUMENTS: LegalDocument[] = [
  {
    id: "DOC-001",
    code: "31/2024/QH15",
    title: "Luật Đất đai năm 2024",
    category: "LAW",
    issuer: "Quốc hội",
    issueDate: "2024-01-18",
    effectiveDate: "2024-08-01",
    status: "EFFECTIVE",
    scope: "M6 – Bồi thường & GPMB",
    summary:
      "Quy định nguyên tắc bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất; thủ tục niêm yết công khai phương án bồi thường bắt buộc 10 ngày (Điều 87).",
    fileType: "PDF",
    fileSize: "4.8 MB",
    downloads: 142,
    tags: ["Thu hồi đất", "GPMB", "Giá đất", "Tái định cư"],
  },
  {
    id: "DOC-002",
    code: "50/2014/QH13",
    title: "Luật Xây dựng (sửa đổi, bổ sung 62/2020/QH14)",
    category: "LAW",
    issuer: "Quốc hội",
    issueDate: "2014-06-18",
    effectiveDate: "2015-01-01",
    status: "EFFECTIVE",
    scope: "M2, M3 – Quản lý dự án & thủ tục XDCB",
    summary:
      "Quy định quyền và nghĩa vụ của chủ đầu tư, ban quản lý dự án chuyên ngành; trình tự thủ tục lập, thẩm định, phê duyệt và nghiệm thu công trình xây dựng.",
    fileType: "PDF",
    fileSize: "3.2 MB",
    downloads: 98,
    tags: ["Xây dựng", "Chủ đầu tư", "Thẩm định", "Nghiệm thu"],
  },
  {
    id: "DOC-003",
    code: "22/2023/QH15",
    title: "Luật Đấu thầu năm 2023",
    category: "LAW",
    issuer: "Quốc hội",
    issueDate: "2023-06-23",
    effectiveDate: "2024-01-01",
    status: "EFFECTIVE",
    scope: "M7 – Quản lý đấu thầu 9 bước",
    summary:
      "Quy định quy trình lựa chọn nhà thầu qua mạng, các bước phê duyệt kế hoạch lựa chọn nhà thầu, HSMT, đánh giá HSDT và ký kết hợp đồng thi công.",
    fileType: "PDF",
    fileSize: "2.9 MB",
    downloads: 87,
    tags: ["Đấu thầu", "Lựa chọn nhà thầu", "HSMT", "KHLCNT"],
  },
  {
    id: "DOC-004",
    code: "10/2021/NĐ-CP",
    title: "Nghị định 10/2021/NĐ-CP về quản lý chi phí đầu tư xây dựng",
    category: "DECREE",
    issuer: "Chính phủ",
    issueDate: "2021-02-09",
    effectiveDate: "2021-02-09",
    status: "EFFECTIVE",
    scope: "M4 – Tài chính & Quyết toán KBNN",
    summary:
      "Quy định lập và quản lý chi phí đầu tư xây dựng, quản lý định mức, đơn giá, kiểm soát thanh toán vốn đầu tư công và quyết toán dự án hoàn thành theo bước 4 KBNN.",
    fileType: "PDF",
    fileSize: "1.8 MB",
    downloads: 115,
    tags: ["Chi phí", "Dự toán", "Quyết toán", "KBNN"],
  },
  {
    id: "DOC-005",
    code: "24/2024/NĐ-CP",
    title: "Nghị định 24/2024/NĐ-CP quy định chi tiết thi hành Luật Đấu thầu",
    category: "DECREE",
    issuer: "Chính phủ",
    issueDate: "2024-02-27",
    effectiveDate: "2024-02-27",
    status: "EFFECTIVE",
    scope: "M7 – Quản lý đấu thầu",
    summary:
      "Quy định biểu mẫu lập E-HSMT, tiêu chuẩn đánh giá hồ sơ dự thầu, trình tự thẩm định và phê duyệt kết quả lựa chọn nhà thầu xây lắp và tư vấn.",
    fileType: "PDF",
    fileSize: "5.1 MB",
    downloads: 76,
    tags: ["Đấu thầu", "E-HSMT", "Tiêu chuẩn đánh giá"],
  },
  {
    id: "DOC-006",
    code: "18/2024/QĐ-UBND",
    title: "Quyết định 18/2024/QĐ-UBND quy định bồi thường, hỗ trợ, TĐC tỉnh Kiên Giang",
    category: "LOCAL",
    issuer: "UBND tỉnh Kiên Giang",
    issueDate: "2024-08-15",
    effectiveDate: "2024-09-01",
    status: "EFFECTIVE",
    scope: "M6 – Bồi thường & GPMB Hà Tiên",
    summary:
      "Quy định chi tiết đơn giá cây trồng, vật kiến trúc, chính sách hỗ trợ chuyển đổi nghề nghiệp và bố trí tái định cư trên địa bàn TP Hà Tiên và tỉnh Kiên Giang.",
    fileType: "PDF",
    fileSize: "2.1 MB",
    downloads: 210,
    tags: ["Kiên Giang", "Đơn giá bồi thường", "GPMB Hà Tiên", "Tái định cư"],
  },
  {
    id: "DOC-007",
    code: "Mẫu 04-GPMB",
    title: "Biên bản niêm yết công khai phương án bồi thường, hỗ trợ GPMB",
    category: "TEMPLATE",
    issuer: "BQL ĐTXD Hà Tiên",
    issueDate: "2026-01-10",
    effectiveDate: "2026-01-10",
    status: "EFFECTIVE",
    scope: "M6 – Bước 6 quy trình GPMB (Bắt buộc 10 ngày)",
    summary:
      "Biểu mẫu chuẩn để Tổ Bồi thường phối hợp UBND phường/xã lập biên bản niêm yết phương án bồi thường tại trụ sở và khu dân cư theo luật định.",
    fileType: "DOCX",
    fileSize: "145 KB",
    downloads: 168,
    tags: ["Biểu mẫu", "Niêm yết", "Bước 6 GPMB", "Biên bản"],
  },
  {
    id: "DOC-008",
    code: "Mẫu HĐ-XL-05",
    title: "Hợp đồng thi công xây dựng mẫu (có cam kết bảo lãnh bảo hành 5%)",
    category: "TEMPLATE",
    issuer: "BQL ĐTXD Hà Tiên",
    issueDate: "2025-12-05",
    effectiveDate: "2026-01-01",
    status: "EFFECTIVE",
    scope: "M4, M8 – Hợp đồng & Bảo lãnh bảo hành",
    summary:
      "Mẫu hợp đồng thi công xây lắp áp dụng cho các gói thầu của Ban; quy định nghĩa vụ nộp bảo lãnh bảo hành bằng 5% giá trị hợp đồng trước khi nghiệm thu bàn giao.",
    fileType: "DOCX",
    fileSize: "280 KB",
    downloads: 195,
    tags: ["Biểu mẫu", "Hợp đồng thi công", "Bảo lãnh bảo hành 5%"],
  },
  {
    id: "DOC-009",
    code: "12/2021/TT-BXD",
    title: "Thông tư 12/2021/TT-BXD ban hành định mức xây dựng",
    category: "CIRCULAR",
    issuer: "Bộ Xây dựng",
    issueDate: "2021-08-31",
    effectiveDate: "2021-10-15",
    status: "EFFECTIVE",
    scope: "M2, M4 – Dự toán & Khối lượng",
    summary:
      "Tập định mức dự toán xây dựng công trình, định mức chi phí quản lý dự án và tư vấn đầu tư xây dựng công trình sử dụng vốn đầu tư công.",
    fileType: "PDF",
    fileSize: "12.4 MB",
    downloads: 64,
    tags: ["Định mức", "Dự toán", "Bộ Xây dựng"],
  },
  {
    id: "DOC-010",
    code: "Mẫu BB-NT-08",
    title: "Biên bản nghiệm thu hoàn thành công trình đưa vào sử dụng",
    category: "TEMPLATE",
    issuer: "BQL ĐTXD Hà Tiên",
    issueDate: "2026-02-01",
    effectiveDate: "2026-02-01",
    status: "EFFECTIVE",
    scope: "M3, M8 – Nghiệm thu & Bắt đầu tính bảo hành",
    summary:
      "Biên bản nghiệm thu chính thức giữa Chủ đầu tư, Tư vấn giám sát và Nhà thầu thi công; làm căn cứ tính mốc bắt đầu thời hạn bảo hành công trình (M8).",
    fileType: "DOCX",
    fileSize: "172 KB",
    downloads: 134,
    tags: ["Biểu mẫu", "Nghiệm thu hoàn thành", "Bàn giao"],
  },
];

export const INITIAL_CHAT_MESSAGES = [
  {
    id: "msg-1",
    sender: "ai" as const,
    text: "Xin chào! Tôi là Trợ lý AI Pháp lý của Ban Quản lý Dự án ĐTXD Hà Tiên. Tôi có thể hỗ trợ bạn tra cứu văn bản quy phạm pháp luật, kiểm tra quy chuẩn thời hạn các bước quy trình (GPMB, Đấu thầu, Nghiệm thu, Bảo hành), hoặc tự động tổng hợp báo cáo văn bản lời từ số liệu thực tế của hệ thống. Bạn cần hỗ trợ gì hôm nay?",
    timestamp: "Vừa xong",
    citations: [],
  },
];

export const AI_SUGGESTED_QUESTIONS = [
  "Thời hạn bắt buộc niêm yết công khai phương án GPMB là bao nhiêu ngày theo Luật Đất đai 2024?",
  "Điều kiện và thủ tục hoàn trả bảo lãnh bảo hành (5%) cho nhà thầu xây lắp?",
  "Hạn mức và hồ sơ thanh toán khối lượng hoàn thành qua KBNN Hà Tiên gồm những gì?",
  "Các mốc thời hạn cảnh báo đỏ trong quy trình GPMB 16 bước?",
];
