/**
 * procedure-steps-master.ts — Danh mục 16 bước chuẩn hóa Quy trình thủ tục XDCB
 *
 * Căn cứ bảng 4.3.2 Cấu trúc quy trình:
 * Gồm 7 nhóm lớn (I đến VII), 9 bước bắt buộc và 7 bước điều kiện linh hoạt.
 */

export interface MasterStepDefinition {
  id: string;
  order: number;
  code: string;
  groupCode: string;
  groupTitle: string;
  name: string;
  type: "MANDATORY" | "CONDITIONAL";
  responsibleUnit: string;
  durationMargin: string;
  durationDaysMin: number | null;
  durationDaysMax: number | null;
  defaultDays: number;
  isContractBased?: boolean;
  isSpecialRequest?: boolean;
  description: string;
}

export const MASTER_PROCEDURE_STEPS: MasterStepDefinition[] = [
  {
    id: "step-1",
    order: 1,
    code: "I",
    groupCode: "I",
    groupTitle: "Giai đoạn Chuẩn bị Dự án & Chủ trương",
    name: "Phê duyệt chủ trương đầu tư",
    type: "MANDATORY",
    responsibleUnit: "Chủ đầu tư + HĐ TĐ Phường",
    durationMargin: "5–10 ngày",
    durationDaysMin: 5,
    durationDaysMax: 10,
    defaultDays: 7,
    description: "Trình duyệt chủ trương đầu tư, thông qua Hội đồng thẩm định và ra quyết định phê duyệt chủ trương.",
  },
  {
    id: "step-2",
    order: 2,
    code: "II",
    groupCode: "II",
    groupTitle: "Nhiệm vụ & Khảo sát BCNCKT / BCKTKT",
    name: "Lập nhiệm vụ KS, BCNCKT/BCKTKT",
    type: "MANDATORY",
    responsibleUnit: "Chủ đầu tư + TV",
    durationMargin: "5–7 ngày",
    durationDaysMin: 5,
    durationDaysMax: 7,
    defaultDays: 6,
    description: "Lập và phê duyệt nhiệm vụ khảo sát xây dựng, đề cương lập Báo cáo nghiên cứu khả thi / Báo cáo kinh tế - kỹ thuật.",
  },
  {
    id: "step-2-1",
    order: 3,
    code: "II.1",
    groupCode: "II",
    groupTitle: "Nhiệm vụ & Khảo sát BCNCKT / BCKTKT",
    name: "Chỉ định thầu TV BCNCKT/BCKTKT",
    type: "CONDITIONAL",
    responsibleUnit: "Chủ đầu tư",
    durationMargin: "5–10 ngày",
    durationDaysMin: 5,
    durationDaysMax: 10,
    defaultDays: 7,
    description: "Áp dụng đối với các gói thầu tư vấn lập BCNCKT/BCKTKT đủ điều kiện chỉ định thầu theo quy định Luật Đấu thầu.",
  },
  {
    id: "step-3",
    order: 4,
    code: "III",
    groupCode: "III",
    groupTitle: "Đấu thầu Tư vấn Lập dự án",
    name: "Đấu thầu TV (chi phí >500 triệu)",
    type: "CONDITIONAL",
    responsibleUnit: "Chủ đầu tư + TV đấu thầu",
    durationMargin: "40–45 ngày",
    durationDaysMin: 40,
    durationDaysMax: 45,
    defaultDays: 42,
    description: "Bắt buộc tổ chức đấu thầu rộng rãi qua mạng nếu chi phí tư vấn lập dự án vượt hạn mức 500 triệu đồng.",
  },
  {
    id: "step-4",
    order: 5,
    code: "IV",
    groupCode: "IV",
    groupTitle: "Lập & Thẩm tra Hồ sơ BCNCKT / BCKTKT",
    name: "TV lập hồ sơ BCNCKT/BCKTKT",
    type: "MANDATORY",
    responsibleUnit: "Tư vấn lập",
    durationMargin: "15–60 ngày",
    durationDaysMin: 15,
    durationDaysMax: 60,
    defaultDays: 30,
    description: "Đơn vị tư vấn thực hiện khảo sát hiện trường, lập hồ sơ thuyết minh và thiết kế cơ sở / bản vẽ thi công.",
  },
  {
    id: "step-4-1",
    order: 6,
    code: "IV.1",
    groupCode: "IV",
    groupTitle: "Lập & Thẩm tra Hồ sơ BCNCKT / BCKTKT",
    name: "Thẩm tra BCNCKT/BCKTKT",
    type: "MANDATORY",
    responsibleUnit: "Tư vấn thẩm tra",
    durationMargin: "10–20 ngày",
    durationDaysMin: 10,
    durationDaysMax: 20,
    defaultDays: 15,
    description: "Tư vấn độc lập thẩm tra sự phù hợp quy chuẩn kỹ thuật, giải pháp kết cấu và dự toán chi phí.",
  },
  {
    id: "step-4-2",
    order: 7,
    code: "IV.2",
    groupCode: "IV",
    groupTitle: "Lập & Thẩm tra Hồ sơ BCNCKT / BCKTKT",
    name: "Thẩm định giá",
    type: "CONDITIONAL",
    responsibleUnit: "Cơ quan thẩm định giá",
    durationMargin: "7–15 ngày",
    durationDaysMin: 7,
    durationDaysMax: 15,
    defaultDays: 10,
    description: "Áp dụng khi cần chứng thư thẩm định giá thiết bị, vật tư công nghệ hoặc định giá tài sản liên quan.",
  },
  {
    id: "step-4-3",
    order: 8,
    code: "IV.3",
    groupCode: "IV",
    groupTitle: "Lập & Thẩm tra Hồ sơ BCNCKT / BCKTKT",
    name: "Lấy ý kiến các sở/ban/ngành (PCCC, ĐTM...)",
    type: "CONDITIONAL",
    responsibleUnit: "Cơ quan chuyên ngành",
    durationMargin: "Theo yêu cầu",
    durationDaysMin: null,
    durationDaysMax: null,
    defaultDays: 15,
    isSpecialRequest: true,
    description: "Lấy ý kiến chuyên môn về thẩm duyệt PCCC, đánh giá tác động môi trường (ĐTM), thỏa thuận quy hoạch, giao thông kết nối.",
  },
  {
    id: "step-5",
    order: 9,
    code: "V",
    groupCode: "V",
    groupTitle: "Thẩm định & Phê duyệt Dự án",
    name: "Thẩm định & phê duyệt BCNCKT/BCKTKT",
    type: "MANDATORY",
    responsibleUnit: "Cơ quan chuyên môn",
    durationMargin: "~20 ngày",
    durationDaysMin: 18,
    durationDaysMax: 22,
    defaultDays: 20,
    description: "Cơ quan chuyên môn về xây dựng (Sở Xây dựng / Phòng QLĐT) thẩm định và Người có thẩm quyền ra quyết định phê duyệt dự án.",
  },
  {
    id: "step-5-1",
    order: 10,
    code: "V.1",
    groupCode: "V",
    groupTitle: "Thẩm định & Phê duyệt Dự án",
    name: "Thẩm định TKBVTC",
    type: "CONDITIONAL",
    responsibleUnit: "Cơ quan chuyên môn",
    durationMargin: "~20 ngày",
    durationDaysMin: 18,
    durationDaysMax: 22,
    defaultDays: 20,
    description: "Áp dụng cho dự án thiết kế 3 bước: thẩm định thiết kế bản vẽ thi công và dự toán sau bước phê duyệt BCNCKT.",
  },
  {
    id: "step-5-2",
    order: 11,
    code: "V.2",
    groupCode: "V",
    groupTitle: "Thẩm định & Phê duyệt Dự án",
    name: "Chỉ định thầu xây lắp",
    type: "CONDITIONAL",
    responsibleUnit: "Chủ đầu tư",
    durationMargin: "5–7 ngày",
    durationDaysMin: 5,
    durationDaysMax: 7,
    defaultDays: 6,
    description: "Áp dụng cho gói thầu xây lắp khẩn cấp, cấp bách hoặc trong hạn mức chỉ định thầu dưới 1 tỷ đồng.",
  },
  {
    id: "step-6",
    order: 12,
    code: "VI",
    groupCode: "VI",
    groupTitle: "Lựa chọn Nhà thầu & Thi công Xây lắp",
    name: "Đấu thầu xây lắp",
    type: "MANDATORY",
    responsibleUnit: "Chủ đầu tư + TV đấu thầu",
    durationMargin: "30–45 ngày",
    durationDaysMin: 30,
    durationDaysMax: 45,
    defaultDays: 35,
    description: "Lập E-HSMT, phát hành qua Hệ thống mạng đấu thầu quốc gia, mở thầu, đánh giá E-HSDT và thương thảo ký kết hợp đồng.",
  },
  {
    id: "step-6-1",
    order: 13,
    code: "VI.1",
    groupCode: "VI",
    groupTitle: "Lựa chọn Nhà thầu & Thi công Xây lắp",
    name: "Thi công – Giám sát kỹ thuật",
    type: "MANDATORY",
    responsibleUnit: "NT + TVGS + Chủ đầu tư",
    durationMargin: "Theo HĐ",
    durationDaysMin: null,
    durationDaysMax: null,
    defaultDays: 180,
    isContractBased: true,
    description: "Triển khai thi công tại hiện trường, tư vấn giám sát nghiệm thu từng hạng mục, quản lý an toàn lao động và môi trường.",
  },
  {
    id: "step-6-2",
    order: 14,
    code: "VI.2",
    groupCode: "VI",
    groupTitle: "Lựa chọn Nhà thầu & Thi công Xây lắp",
    name: "Nghiệm thu hoàn thành",
    type: "MANDATORY",
    responsibleUnit: "NT + Chủ đầu tư",
    durationMargin: "Theo HĐ",
    durationDaysMin: null,
    durationDaysMax: null,
    defaultDays: 15,
    isContractBased: true,
    description: "Tổ chức nghiệm thu hoàn thành công trình đưa vào sử dụng, bàn giao tài sản cho đơn vị thụ hưởng.",
  },
  {
    id: "step-6-3",
    order: 15,
    code: "VI.3",
    groupCode: "VI",
    groupTitle: "Lựa chọn Nhà thầu & Thi công Xây lắp",
    name: "Kiểm toán độc lập",
    type: "CONDITIONAL",
    responsibleUnit: "Tổ chức kiểm toán",
    durationMargin: "Theo HĐ",
    durationDaysMin: null,
    durationDaysMax: null,
    defaultDays: 30,
    isContractBased: true,
    description: "Thuê đơn vị kiểm toán độc lập kiểm toán báo cáo quyết toán vốn đầu tư hoàn thành đối với dự án có quy mô vốn quy định.",
  },
  {
    id: "step-7",
    order: 16,
    code: "VII",
    groupCode: "VII",
    groupTitle: "Quyết toán & Bảo hành Công trình",
    name: "Quyết toán – Bảo hành",
    type: "MANDATORY",
    responsibleUnit: "Chủ đầu tư + NT",
    durationMargin: "Theo HĐ",
    durationDaysMin: null,
    durationDaysMax: null,
    defaultDays: 60,
    isContractBased: true,
    description: "Phê duyệt quyết toán vốn đầu tư dự án hoàn thành, quản lý thời gian bảo hành và giải tỏa tiền giữ lại theo hợp đồng.",
  },
];
