import type { FinanceDataset } from "../types/finance.types";

export const FINANCE_MOCK_DATA: FinanceDataset = {
  projects: [
    {
      id: "PRJ-001",
      code: "BQL-DA-2026-001",
      name: "Nâng cấp tuyến đường ven biển Hòn Chông",
      totalInvestment: 185.4,
      status: "Đang thực hiện",
    },
    {
      id: "PRJ-002",
      code: "BQL-DA-2026-002",
      name: "Kè chống sạt lở bờ biển Thuận Yên",
      totalInvestment: 96.75,
      status: "Đang thực hiện",
    },
    {
      id: "PRJ-003",
      code: "BQL-DA-2025-014",
      name: "Cầu dân sinh kênh T4",
      totalInvestment: 42.8,
      status: "Chờ quyết toán",
    },
    {
      id: "PRJ-004",
      code: "BQL-DA-2024-008",
      name: "Trụ sở hành chính phường Đông Hồ",
      totalInvestment: 31.2,
      status: "Chờ quyết toán",
    },
  ],
  contracts: [
    {
      id: "CTR-001",
      code: "12/2026/HĐ-XL",
      projectId: "PRJ-001",
      contractor: "Công ty CP Xây dựng Kiên Giang",
      value: 72.5,
      disbursed: 69.2,
    },
    {
      id: "CTR-002",
      code: "18/2026/HĐ-TVGS",
      projectId: "PRJ-001",
      contractor: "Công ty Tư vấn Nam Việt",
      value: 4.8,
      disbursed: 2.1,
    },
    {
      id: "CTR-003",
      code: "07/2026/HĐ-XL",
      projectId: "PRJ-002",
      contractor: "Liên danh Mekong – An Giang",
      value: 61.2,
      disbursed: 38.4,
    },
    {
      id: "CTR-004",
      code: "31/2025/HĐ-XL",
      projectId: "PRJ-003",
      contractor: "Công ty TNHH Cầu đường 68",
      value: 35.6,
      disbursed: 35.6,
    },
  ],
  treasuryAccounts: [
    {
      id: "KBNN-01",
      number: "9527.1.1068266",
      bankName: "KBNN Hà Tiên",
      label: "Tài khoản vốn đầu tư công",
    },
    {
      id: "KBNN-02",
      number: "9527.2.1068266",
      bankName: "KBNN Hà Tiên",
      label: "Tài khoản vốn ngân sách tỉnh",
    },
  ],
  capitalPlans: [
    {
      id: "PLAN-001",
      projectId: "PRJ-001",
      year: 2026,
      source: "Ngân sách tỉnh",
      initialAmount: 65,
      adjustmentAmount: 8.5,
      approvalDocument: "QĐ 318/QĐ-UBND",
      approvalFileName: "QD-318-dieu-chinh-von.pdf",
      updatedAt: "2026-07-18",
    },
    {
      id: "PLAN-002",
      projectId: "PRJ-001",
      year: 2026,
      source: "Ngân sách Trung ương",
      initialAmount: 30,
      adjustmentAmount: 0,
      updatedAt: "2026-01-12",
    },
    {
      id: "PLAN-003",
      projectId: "PRJ-002",
      year: 2026,
      source: "Vốn đầu tư công",
      initialAmount: 52,
      adjustmentAmount: -4,
      approvalDocument: "QĐ 402/QĐ-UBND",
      approvalFileName: "QD-402-dieu-chinh-von.pdf",
      updatedAt: "2026-08-02",
    },
    {
      id: "PLAN-004",
      projectId: "PRJ-003",
      year: 2026,
      source: "Ngân sách tỉnh",
      initialAmount: 18,
      adjustmentAmount: 2,
      approvalDocument: "QĐ 291/QĐ-UBND",
      approvalFileName: "QD-291-bo-sung-von.pdf",
      updatedAt: "2026-06-26",
    },
    {
      id: "PLAN-005",
      projectId: "PRJ-004",
      year: 2026,
      source: "Nguồn thu hợp pháp",
      initialAmount: 12.5,
      adjustmentAmount: 0,
      updatedAt: "2026-01-15",
    },
  ],
  disbursements: [
    {
      id: "DIS-001",
      code: "GN-2026-038",
      projectId: "PRJ-001",
      payee: "Công ty CP Xây dựng Kiên Giang",
      content: "Thanh toán khối lượng xây lắp hoàn thành đợt 4",
      amount: 18.7,
      contractId: "CTR-001",
      approvalDate: "2026-09-12",
      dueDate: "2026-09-18",
      treasuryAccountId: "KBNN-01",
      evidence: [{ id: "FILE-001", name: "to-trinh-dot-4.pdf", size: "2,4 MB" }],
      status: "PENDING_DIRECTOR",
      approvals: [
        { role: "Kế toán viên", actor: "Nguyễn Thị Thúy Hà", at: "2026-09-12 09:20", action: "Khởi tạo" },
        { role: "Kế toán trưởng", actor: "Đặng Thị Kim Ngân", at: "2026-09-13 14:10", action: "Đã duyệt" },
      ],
      createdAt: "2026-09-12",
    },
    {
      id: "DIS-002",
      code: "GN-2026-039",
      projectId: "PRJ-002",
      payee: "Liên danh Mekong – An Giang",
      content: "Thanh toán giá trị nghiệm thu tháng 8/2026",
      amount: 11.25,
      contractId: "CTR-003",
      approvalDate: "2026-09-14",
      dueDate: "2026-09-21",
      treasuryAccountId: "KBNN-02",
      evidence: [
        { id: "FILE-002", name: "de-nghi-thanh-toan.pdf", size: "1,8 MB" },
        { id: "FILE-003", name: "bien-ban-nghiem-thu.pdf", size: "3,2 MB" },
      ],
      status: "PENDING_CHIEF",
      approvals: [
        { role: "Kế toán viên", actor: "Nguyễn Thị Thúy Hà", at: "2026-09-14 15:40", action: "Khởi tạo" },
      ],
      createdAt: "2026-09-14",
    },
    {
      id: "DIS-003",
      code: "GN-2026-036",
      projectId: "PRJ-001",
      payee: "Công ty Tư vấn Nam Việt",
      content: "Thanh toán tư vấn giám sát quý III",
      amount: 0.85,
      contractId: "CTR-002",
      approvalDate: "2026-09-05",
      dueDate: "2026-09-11",
      treasuryAccountId: "KBNN-01",
      evidence: [{ id: "FILE-004", name: "uy-nhiem-chi.pdf", size: "760 KB" }],
      status: "APPROVED",
      approvals: [
        { role: "Kế toán viên", actor: "Nguyễn Thị Thúy Hà", at: "2026-09-05 08:30", action: "Khởi tạo" },
        { role: "Kế toán trưởng", actor: "Đặng Thị Kim Ngân", at: "2026-09-06 10:05", action: "Đã duyệt" },
        { role: "Giám đốc", actor: "Huỳnh Thái Hải", at: "2026-09-07 16:15", action: "Phê duyệt" },
      ],
      createdAt: "2026-09-05",
    },
    {
      id: "DIS-004",
      code: "GN-2026-031",
      projectId: "PRJ-003",
      payee: "Công ty TNHH Cầu đường 68",
      content: "Thanh toán quyết toán hợp đồng xây lắp",
      amount: 6.4,
      contractId: "CTR-004",
      approvalDate: "2026-08-25",
      dueDate: "2026-09-02",
      treasuryAccountId: "KBNN-02",
      evidence: [{ id: "FILE-005", name: "ho-so-quyet-toan.pdf", size: "5,1 MB" }],
      status: "APPROVED",
      approvals: [
        { role: "Kế toán viên", actor: "Nguyễn Thị Thúy Hà", at: "2026-08-25 09:00", action: "Khởi tạo" },
        { role: "Kế toán trưởng", actor: "Đặng Thị Kim Ngân", at: "2026-08-26 11:20", action: "Đã duyệt" },
        { role: "Giám đốc", actor: "Huỳnh Thái Hải", at: "2026-08-27 15:10", action: "Phê duyệt" },
      ],
      createdAt: "2026-08-25",
    },
    {
      id: "DIS-005",
      code: "GN-2026-030",
      projectId: "PRJ-002",
      payee: "Liên danh Mekong – An Giang",
      content: "Đề nghị tạm ứng đợt 2 vật tư thi công kè bờ biển",
      amount: 5.5,
      contractId: "CTR-003",
      approvalDate: "2026-08-10",
      dueDate: "2026-08-18",
      treasuryAccountId: "KBNN-02",
      evidence: [{ id: "FILE-006", name: "de-nghi-tam-ung.pdf", size: "1,1 MB" }],
      status: "REJECTED",
      rejectionReason: "Thiếu chứng thư bảo lãnh tạm ứng hợp đồng từ ngân hàng thương mại theo quy định tại NĐ 24/2024/NĐ-CP.",
      approvals: [
        { role: "Kế toán viên", actor: "Nguyễn Thị Thúy Hà", at: "2026-08-10 10:15", action: "Khởi tạo" },
        { role: "Kế toán trưởng", actor: "Đặng Thị Kim Ngân", at: "2026-08-11 16:30", action: "Từ chối", note: "Yêu cầu bổ sung bảo lãnh tạm ứng" },
      ],
      createdAt: "2026-08-10",
    },
  ],
  settlements: [
    {
      id: "SET-001",
      projectId: "PRJ-003",
      approvedSettlementAmount: 42.8,
      disbursedAmount: 42.8,
      advanceRecovered: true,
      approvedDecisionFile: "QD-phe-duyet-quyet-toan-177.pdf",
      warrantyReturned: false,
      completedSteps: [1],
      status: "IN_PROGRESS",
    },
    {
      id: "SET-002",
      projectId: "PRJ-004",
      approvedSettlementAmount: 31.2,
      disbursedAmount: 30.95,
      advanceRecovered: true,
      warrantyReturned: false,
      completedSteps: [],
      status: "NOT_STARTED",
    },
  ],
};

