import type { PersonnelDataset } from "../types/personnel.types";

/** Dữ liệu mẫu theo cơ cấu BQL ĐTXD Hà Tiên: Ban Giám đốc và 3 tổ chuyên môn (BRD mục 2.1) */
export const PERSONNEL_MOCK_DATA: PersonnelDataset = {
  teams: [
    { id: "BGD", name: "Ban Giám đốc", description: "", leaderId: "ST-001" },
    { id: "GSKT", name: "Tổ Giám sát – Kỹ thuật", description: "", leaderId: "ST-004" },
    { id: "HCTH", name: "Tổ Hành chính – Tổng hợp", description: "", leaderId: "ST-009" },
    { id: "BT", name: "Tổ Bồi thường – GPMB – TĐC", description: "", leaderId: "ST-014" },
  ],
  staff: [
    { id: "ST-001", name: "Huỳnh Thái Hải", title: "Giám đốc", teamId: "BGD", roleCode: "ADMIN", employment: "Viên chức", phone: "0918.xxx.xxx", email: "hai.ht@hatien.gov.vn", accountActive: true },
    { id: "ST-002", name: "Trần Văn Nam", title: "Phó Giám đốc", teamId: "BGD", roleCode: "DEPUTY_DIRECTOR", employment: "Viên chức", phone: "0913.xxx.xxx", email: "nam.tv@hatien.gov.vn", accountActive: true },
    { id: "ST-003", name: "Nguyễn Thanh Tùng", title: "Phó Giám đốc", teamId: "BGD", roleCode: "DEPUTY_DIRECTOR", employment: "Viên chức", phone: "0939.xxx.xxx", email: "tung.nt@hatien.gov.vn", accountActive: true },
    { id: "ST-004", name: "Lê Hoàng Minh", title: "Tổ trưởng", teamId: "GSKT", roleCode: "TECHNICAL_OFFICER", employment: "Viên chức", phone: "0982.xxx.xxx", email: "minh.lh@hatien.gov.vn", accountActive: true, permissions: ["project.phase.assign", "project.progress.update", "project.report.export"] },
    { id: "ST-005", name: "Phan Văn Đức", title: "Kỹ sư giám sát", teamId: "GSKT", roleCode: "TECHNICAL_OFFICER", employment: "Viên chức", phone: "0907.xxx.xxx", email: "duc.pv@hatien.gov.vn", accountActive: true, permissions: ["project.phase.assign", "project.progress.update", "project.report.export"] },
    { id: "ST-006", name: "Trần Quốc Việt", title: "Kỹ sư giám sát", teamId: "GSKT", roleCode: "TECHNICAL_OFFICER", employment: "Viên chức", phone: "0976.xxx.xxx", email: "viet.tq@hatien.gov.vn", accountActive: true },
    { id: "ST-007", name: "Nguyễn Hữu Phước", title: "Kỹ sư dự toán", teamId: "GSKT", roleCode: "TECHNICAL_OFFICER", employment: "Viên chức", phone: "0944.xxx.xxx", email: "phuoc.nh@hatien.gov.vn", accountActive: false, lockReason: "" },
    { id: "ST-008", name: "Lâm Thị Diễm", title: "Kỹ sư giám sát", teamId: "GSKT", roleCode: "TECHNICAL_OFFICER", employment: "Hợp đồng", phone: "0916.xxx.xxx", email: "diem.lt@hatien.gov.vn", accountActive: true, permissions: ["project.progress.update"] },
    { id: "ST-009", name: "Đặng Thị Kim Ngân", title: "Kế toán trưởng", teamId: "HCTH", roleCode: "CHIEF_ACCOUNTANT", employment: "Viên chức", phone: "0908.xxx.xxx", email: "ngan.dtk@hatien.gov.vn", accountActive: true },
    { id: "ST-010", name: "Nguyễn Thị Thúy Hà", title: "Kế toán viên", teamId: "HCTH", roleCode: "ACCOUNTANT", employment: "Viên chức", phone: "0977.xxx.xxx", email: "ha.ntt@hatien.gov.vn", accountActive: true },
    { id: "ST-011", name: "Lê Thị Hồng", title: "Kế toán viên", teamId: "HCTH", roleCode: "ACCOUNTANT", employment: "Viên chức", phone: "0931.xxx.xxx", email: "hong.lt@hatien.gov.vn", accountActive: true },
    { id: "ST-012", name: "Võ Thị Mai Phương", title: "Chuyên viên văn thư", teamId: "HCTH", roleCode: "ADMINISTRATIVE_OFFICER", employment: "Viên chức", phone: "0932.xxx.xxx", email: "phuong.vtm@hatien.gov.vn", accountActive: true },
    { id: "ST-013", name: "Châu Văn Lợi", title: "Nhân viên hành chính", teamId: "HCTH", roleCode: "ADMINISTRATIVE_OFFICER", employment: "Hợp đồng", phone: "0949.xxx.xxx", email: "loi.cv@hatien.gov.vn", accountActive: true },
    { id: "ST-014", name: "Phạm Quốc Bảo", title: "Tổ trưởng", teamId: "BT", roleCode: "COMPENSATION_OFFICER", employment: "Viên chức", phone: "0945.xxx.xxx", email: "bao.pq@hatien.gov.vn", accountActive: true },
    { id: "ST-015", name: "Huỳnh Văn Tài", title: "Chuyên viên bồi thường", teamId: "BT", roleCode: "COMPENSATION_OFFICER", employment: "Viên chức", phone: "0919.xxx.xxx", email: "tai.hv@hatien.gov.vn", accountActive: true },
    { id: "ST-016", name: "Đỗ Thị Thanh", title: "Chuyên viên bồi thường", teamId: "BT", roleCode: "COMPENSATION_OFFICER", employment: "Hợp đồng", phone: "0962.xxx.xxx", email: "thanh.dt@hatien.gov.vn", accountActive: true },
  ],
  projects: [
    {
      id: "PRJ-001",
      code: "BQL-DA-2026-001",
      name: "Kè bảo vệ bờ biển phường Pháo Đài",
      status: "Đang thi công",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      mainExecutorId: "ST-005",
      mainSupervisorId: "ST-003",
      assignedAt: "2026-10-08",
      actingDirectorId: "ST-005",
      actingDirectorAssignedAt: "2026-10-08",
      actingDirectorAssignedBy: "Huỳnh Thái Hải",
      teamMembers: ["ST-005", "ST-003", "ST-004", "ST-006"],
    },
    {
      id: "PRJ-002",
      code: "BQL-DA-2026-002",
      name: "Tuyến đường ven biển phường Pháo Đài",
      status: "Nghiệm thu hoàn thành",
      startDate: "2025-06-15",
      endDate: "2026-06-30",
      mainExecutorId: "ST-005",
      mainSupervisorId: "ST-002",
      assignedAt: "2026-01-10",
      directorApprovalStatus: "PENDING",
      directorSubmittedAt: "2026-10-08",
      directorSubmittedBy: "Phan Văn Đức (Chủ nhiệm dự án)",
      directorTargetRole: "GIAM_DOC",
      directorTargetStaffName: "Huỳnh Thái Hải",
      directorSubmissionNote: "Toàn bộ 7 giai đoạn thực hiện dự án đã hoàn thành nghiệm thu đạt yêu cầu. Kính trình Giám đốc xem xét phê duyệt kết thúc dự án.",
      actingDirectorId: "ST-005",
      actingDirectorAssignedAt: "2026-01-10",
      actingDirectorAssignedBy: "Huỳnh Thái Hải",
      teamMembers: ["ST-005", "ST-004", "ST-006", "ST-008", "ST-014"],
    },
    { id: "PRJ-003", code: "BQL-DA-2026-003", name: "Khu dân cư & Tái định cư phường Pháo Đài", status: "Bồi thường GPMB", startDate: "2026-02-01", endDate: "2027-04-30" },
    { id: "PRJ-004", code: "BQL-DA-2026-004", name: "Cầu Tô Châu", status: "Đang thi công", startDate: "2026-01-15", endDate: "2026-11-30" },
    { id: "PRJ-005", code: "BQL-DA-2026-005", name: "Cải tạo Chợ Trung tâm Hà Tiên", status: "Chuẩn bị ĐT", startDate: "2026-03-01", endDate: "2026-10-15" },
    { id: "PRJ-006", code: "BQL-DA-2026-006", name: "Nâng cấp hệ thống thoát nước trung tâm TP Hà Tiên", status: "Đang thi công", startDate: "2026-02-15", endDate: "2026-12-15" },
    { id: "PRJ-007", code: "BQL-DA-2026-007", name: "Công viên cây xanh ven đầm Đông Hồ", status: "Thiết kế BVTC", startDate: "2026-04-01", endDate: "2027-01-20" },
    { id: "PRJ-008", code: "BQL-DA-2026-008", name: "Mở rộng tuyến đường du lịch Mũi Nai", status: "Chuẩn bị ĐT", startDate: "2026-05-01", endDate: "2027-05-01" },
    { id: "PRJ-009", code: "BQL-DA-2026-009", name: "Trường Mầm non Pháo Đài", status: "Đang thi công", startDate: "2026-01-10", endDate: "2026-09-30" },
    { id: "PRJ-010", code: "BQL-DA-2026-010", name: "Trạm y tế phường Tô Châu", status: "Đấu thầu XL", startDate: "2026-03-15", endDate: "2026-11-20" },
    { id: "PRJ-011", code: "BQL-DA-2026-011", name: "Khu tái định cư Núi Đèn", status: "Bồi thường GPMB", startDate: "2026-02-20", endDate: "2027-03-31" },
    { id: "PRJ-012", code: "BQL-DA-2026-012", name: "Hệ thống chiếu sáng công cộng đường Chi Lăng", status: "Đã hoàn thành", startDate: "2025-09-01", endDate: "2026-02-28" },
  ],
  assignments: [
    {
      id: "AS-DEMO-PHASE-001",
      title: "Phụ trách giám sát thi công kè biển",
      projectId: "PRJ-001",
      stage: "VI",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-004",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-10-08",
      dueDate: "2026-11-20",
      status: "IN_PROGRESS",
      priority: "NORMAL",
    },
    {
      id: "AS-DEMO-TASK-001",
      title: "Kiểm tra vật liệu đầu vào công trình kè",
      projectId: "PRJ-001",
      stage: "VI",
      stepCode: "VI.1",
      stepName: "Thi công – Giám sát kỹ thuật",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-006",
      parentAssignmentId: "AS-DEMO-PHASE-001",
      assignedBy: "Lê Hoàng Minh",
      assignedByStaffId: "ST-004",
      assignedByRole: "TEAM_LEAD",
      assignmentLevel: "TASK_MEMBER",
      assignedAt: "2026-10-08",
      dueDate: "2026-10-30",
      status: "PENDING_APPROVAL", // Thành viên Trần Quốc Việt đã hoàn thành và gửi duyệt qua Lead tổ Lê Hoàng Minh
      confirmRequestedAt: "2026-10-08",
      priority: "NORMAL",
      submissions: [
        {
          id: "SUB-DEMO-001",
          documentCode: "BB-NT-VL-001",
          title: "Biên bản kiểm tra và kết quả thí nghiệm vật liệu đá, thép, bê tông đầu vào",
          fileName: "BienBan_KiemTra_VatLieuDauVao_KeBien.pdf",
          fileSize: "3.8 MB",
          submittedAt: "2026-10-08 09:30",
          submittedByStaffId: "ST-006",
          submittedByName: "Trần Quốc Việt",
          leadApprovalStatus: "PENDING_LEAD",
          fileType: "pdf",
        },
        {
          id: "SUB-DEMO-002",
          documentCode: "KQ-TN-002",
          title: "Phiếu kết quả thí nghiệm nén mẫu bê tông R28",
          fileName: "KetQua_ThiNghiem_MauBeTong_R28.pdf",
          fileSize: "1.5 MB",
          submittedAt: "2026-10-08 09:35",
          submittedByStaffId: "ST-006",
          submittedByName: "Trần Quốc Việt",
          leadApprovalStatus: "PENDING_LEAD",
          fileType: "pdf",
        },
      ],
    },
    {
      id: "AS-DEMO-TASK-002",
      title: "Thực hiện [Bước VI.2] Nghiệm thu hoàn thành",
      projectId: "PRJ-001",
      stage: "VI",
      stepCode: "VI.2",
      stepName: "Nghiệm thu hoàn thành",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-004",
      parentAssignmentId: "AS-DEMO-PHASE-001",
      assignedBy: "Lê Hoàng Minh",
      assignedByStaffId: "ST-004",
      assignedByRole: "TEAM_LEAD",
      assignmentLevel: "TASK_MEMBER",
      assignedAt: "2026-10-08",
      dueDate: "2026-11-15",
      status: "TODO",
      priority: "NORMAL",
    },
    {
      id: "AS-DEMO-TASK-003",
      title: "Thực hiện [Bước VI.3] Kiểm toán độc lập",
      projectId: "PRJ-001",
      stage: "VI",
      stepCode: "VI.3",
      stepName: "Kiểm toán độc lập",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-005",
      parentAssignmentId: "AS-DEMO-PHASE-001",
      assignedBy: "Lê Hoàng Minh",
      assignedByStaffId: "ST-004",
      assignedByRole: "TEAM_LEAD",
      assignmentLevel: "TASK_MEMBER",
      assignedAt: "2026-10-08",
      dueDate: "2026-11-20",
      status: "TODO",
      priority: "NORMAL",
    },
    // Dữ liệu mẫu dự án PRJ-002 đã hoàn thành trọn vẹn 7/7 giai đoạn để kiểm thử luồng Trình Ban Giám đốc
    {
      id: "AS-PRJ2-STAGE-1",
      title: "Giai đoạn I: Chuẩn bị Dự án & Chủ trương",
      projectId: "PRJ-002",
      stage: "I",
      teamId: "HCTH",
      teamLeaderId: "ST-009",
      assigneeId: "ST-009",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-01-15",
      dueDate: "2026-02-28",
      status: "DONE",
      completedAt: "2026-02-25",
      priority: "NORMAL",
    },
    {
      id: "AS-PRJ2-STAGE-2",
      title: "Giai đoạn II: Khảo sát & Lập báo cáo kinh tế kỹ thuật",
      projectId: "PRJ-002",
      stage: "II",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-004",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-03-01",
      dueDate: "2026-04-15",
      status: "DONE",
      completedAt: "2026-04-10",
      priority: "NORMAL",
    },
    {
      id: "AS-PRJ2-STAGE-3",
      title: "Giai đoạn III: Đấu thầu Tư vấn & Lựa chọn nhà thầu tư vấn",
      projectId: "PRJ-002",
      stage: "III",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-007",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-04-16",
      dueDate: "2026-05-20",
      status: "DONE",
      completedAt: "2026-05-18",
      priority: "NORMAL",
    },
    {
      id: "AS-PRJ2-STAGE-4",
      title: "Giai đoạn IV: Bồi thường, giải phóng mặt bằng & TĐC",
      projectId: "PRJ-002",
      stage: "IV",
      teamId: "BT",
      teamLeaderId: "ST-014",
      assigneeId: "ST-014",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-05-21",
      dueDate: "2026-07-15",
      status: "DONE",
      completedAt: "2026-07-12",
      priority: "HIGH",
    },
    {
      id: "AS-PRJ2-STAGE-5",
      title: "Giai đoạn V: Thẩm định hồ sơ thiết kế & Phê duyệt",
      projectId: "PRJ-002",
      stage: "V",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-004",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-07-16",
      dueDate: "2026-08-15",
      status: "DONE",
      completedAt: "2026-08-10",
      priority: "NORMAL",
    },
    {
      id: "AS-PRJ2-STAGE-6",
      title: "Giai đoạn VI: Thi công xây lắp công trình tuyến đường",
      projectId: "PRJ-002",
      stage: "VI",
      teamId: "GSKT",
      teamLeaderId: "ST-004",
      assigneeId: "ST-006",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-08-16",
      dueDate: "2026-09-30",
      status: "DONE",
      completedAt: "2026-09-28",
      priority: "HIGH",
    },
    {
      id: "AS-PRJ2-STAGE-7",
      title: "Giai đoạn VII: Nghiệm thu hoàn thành, bàn giao & quyết toán",
      projectId: "PRJ-002",
      stage: "VII",
      teamId: "HCTH",
      teamLeaderId: "ST-009",
      assigneeId: "ST-010",
      assignedBy: "Phan Văn Đức",
      assignedByStaffId: "ST-005",
      assignedByRole: "PROJECT_LEAD",
      assignmentLevel: "PHASE_LEAD",
      assignedAt: "2026-10-01",
      dueDate: "2026-10-07",
      status: "DONE",
      completedAt: "2026-10-07",
      priority: "NORMAL",
    },
  ],
};
