import type { ProjectItem } from "../types/project.types";

export const INITIAL_PROJECTS_MOCK: ProjectItem[] = [
  {
    id: "PRJ-001",
    code: "BQL-DA-2026-001",
    name: "Kè bảo vệ bờ biển phường Pháo Đài (Đoạn xung yếu)",
    type: "Thủy lợi",
    fundingSource: "Ngân sách tỉnh",
    totalInvestment: 125.5,
    plan2026: 85.0,
    disbursedAmount: 52.4,
    managerName: "Lê Hoàng Minh",
    supervisorName: "Nguyễn Văn An",
    startDate: "2025-08-15",
    endDatePlanned: "2026-11-30",
    currentStage: "CONSTRUCTION",
    actualProgress: 62.0,
    plannedProgress: 90.0, // Chậm 28% -> Danger
    status: "active",
    progressHistory: [
      {
        id: "HIS-001-3",
        updatedAt: "2026-06-08",
        updatedBy: "Lê Hoàng Minh",
        oldProgress: 58.0,
        newProgress: 62.0,
        note: "Nhà thầu thiếu hụt nguồn đá hộc san lấp tại mỏ Kiên Lương. Ảnh hưởng thi công đoạn K0+800.",
      },
      {
        id: "HIS-001-2",
        updatedAt: "2026-05-25",
        updatedBy: "Lê Hoàng Minh",
        oldProgress: 52.0,
        newProgress: 58.0,
        note: "Đã đổ bê tông dầm mũ đoạn 1, thời tiết mưa bão làm gián đoạn ép cọc.",
      },
      {
        id: "HIS-001-1",
        updatedAt: "2026-05-11",
        updatedBy: "Lê Hoàng Minh",
        oldProgress: 45.0,
        newProgress: 52.0,
        note: "Hoàn thành 140/200 cọc kè phân đoạn bờ biển phía Nam.",
      },
    ],
  },
  {
    id: "PRJ-002",
    code: "BQL-DA-2026-002",
    name: "Tuyến đường ven biển phường Pháo Đài (Gói XL-02)",
    type: "Giao thông",
    fundingSource: "Ngân sách Trung ương",
    totalInvestment: 185.0,
    plan2026: 120.0,
    disbursedAmount: 89.2,
    managerName: "Nguyễn Văn An",
    supervisorName: "Lê Hoàng Minh",
    startDate: "2025-03-01",
    endDatePlanned: "2026-12-25",
    currentStage: "CONSTRUCTION",
    actualProgress: 74.5,
    plannedProgress: 80.0, // Chậm 5.5% -> Normal
    status: "active",
    progressHistory: [
      {
        id: "HIS-002-2",
        updatedAt: "2026-06-01",
        updatedBy: "Nguyễn Văn An",
        oldProgress: 70.0,
        newProgress: 74.5,
        note: "Hoàn tất thảm bê tông nhựa hạt trung đoạn Km1+200 đến Km2+400. Chờ giải ngân đợt 2 Kho bạc.",
      },
      {
        id: "HIS-002-1",
        updatedAt: "2026-05-18",
        updatedBy: "Nguyễn Văn An",
        oldProgress: 65.0,
        newProgress: 70.0,
        note: "Thi công lắp đặt bó vỉa và hố ga thoát nước dọc tuyến.",
      },
    ],
  },
  {
    id: "PRJ-003",
    code: "BQL-DA-2026-003",
    name: "Khu dân cư & Tái định cư phường Pháo Đài",
    type: "Hạ tầng kỹ thuật",
    fundingSource: "Ngân sách thành phố",
    totalInvestment: 94.2,
    plan2026: 60.0,
    disbursedAmount: 38.5,
    managerName: "Phạm Quốc Bảo",
    supervisorName: "Phạm Quốc Tuấn",
    startDate: "2025-06-10",
    endDatePlanned: "2026-10-15",
    currentStage: "COMPENSATION",
    actualProgress: 88.0,
    plannedProgress: 90.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-003-1",
        updatedAt: "2026-06-05",
        updatedBy: "Phạm Quốc Bảo",
        oldProgress: 85.0,
        newProgress: 88.0,
        note: "Còn 02 hộ dân chưa đồng thuận nhận tiền bồi thường đợt cuối, cần tổ chức đối thoại trực tiếp.",
      },
    ],
  },
  {
    id: "PRJ-004",
    code: "BQL-DA-2026-004",
    name: "Cầu Tô Châu (Nhánh nâng cấp tải trọng & Lối đi bộ)",
    type: "Giao thông",
    fundingSource: "Ngân sách tỉnh",
    totalInvestment: 68.5,
    plan2026: 45.0,
    disbursedAmount: 65.0,
    managerName: "Phạm Quốc Tuấn",
    supervisorName: "Lê Hoàng Minh",
    startDate: "2024-11-01",
    endDatePlanned: "2026-05-30",
    actualEndDate: "2026-05-28",
    currentStage: "COMPLETED",
    actualProgress: 100.0,
    plannedProgress: 100.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-004-2",
        updatedAt: "2026-05-28",
        updatedBy: "Phạm Quốc Tuấn",
        oldProgress: 98.0,
        newProgress: 100.0,
        note: "Đã tổ chức đoàn kiểm tra hiện trường, hoàn thành nghiệm thu bàn giao và chuyển vào bảo hành.",
        actualEndDateRecorded: "2026-05-28",
      },
    ],
  },
  {
    id: "PRJ-005",
    code: "BQL-DA-2026-005",
    name: "Cải tạo, nâng cấp Chợ Trung tâm TP Hà Tiên",
    type: "Dân dụng",
    fundingSource: "Ngân sách thành phố",
    totalInvestment: 45.0,
    plan2026: 30.0,
    disbursedAmount: 12.0,
    managerName: "Nguyễn Văn An",
    supervisorName: "Phạm Quốc Tuấn",
    startDate: "2026-02-01",
    endDatePlanned: "2026-11-20",
    currentStage: "BIDDING",
    actualProgress: 35.0,
    plannedProgress: 35.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-005-1",
        updatedAt: "2026-06-02",
        updatedBy: "Nguyễn Văn An",
        oldProgress: 25.0,
        newProgress: 35.0,
        note: "Hoàn tất phát hành E-HSMT trên Hệ thống Đấu thầu Quốc gia, chuẩn bị mở thầu.",
      },
    ],
  },
  {
    id: "PRJ-006",
    code: "BQL-DA-2026-006",
    name: "Hệ thống thoát nước & Xử lý nước thải đô thị khu Đông Hồ",
    type: "Hạ tầng kỹ thuật",
    fundingSource: "Vốn ODA",
    totalInvestment: 88.0,
    plan2026: 50.0,
    disbursedAmount: 18.6,
    managerName: "Lê Hoàng Minh",
    supervisorName: "Nguyễn Văn An",
    startDate: "2025-10-01",
    endDatePlanned: "2027-04-30",
    currentStage: "DESIGN",
    actualProgress: 42.0,
    plannedProgress: 60.0, // Chậm 18% -> Warning
    status: "active",
    progressHistory: [
      {
        id: "HIS-006-1",
        updatedAt: "2026-05-20",
        updatedBy: "Lê Hoàng Minh",
        oldProgress: 35.0,
        newProgress: 42.0,
        note: "Đang chờ ý kiến thẩm định ĐTM từ Sở Tài nguyên & Môi trường.",
      },
    ],
  },
  {
    id: "PRJ-007",
    code: "BQL-DA-2026-007",
    name: "Trường Tiểu học & THCS Tô Châu (Khối phòng học bộ môn)",
    type: "Dân dụng",
    fundingSource: "Ngân sách thành phố",
    totalInvestment: 36.8,
    plan2026: 25.0,
    disbursedAmount: 34.2,
    managerName: "Phạm Quốc Tuấn",
    supervisorName: "Lê Hoàng Minh",
    startDate: "2025-04-15",
    endDatePlanned: "2026-06-30",
    currentStage: "INSPECTION",
    actualProgress: 95.0,
    plannedProgress: 95.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-007-1",
        updatedAt: "2026-06-08",
        updatedBy: "Phạm Quốc Tuấn",
        oldProgress: 90.0,
        newProgress: 95.0,
        note: "Đang tiến hành nghiệm thu kỹ thuật PCCC và hệ thống điện chiếu sáng nội bộ.",
      },
    ],
  },
  {
    id: "PRJ-008",
    code: "BQL-DA-2026-008",
    name: "Công viên cảnh quan ven biển Mũi Nai",
    type: "Dân dụng",
    fundingSource: "Ngân sách tỉnh",
    totalInvestment: 28.5,
    plan2026: 28.5,
    disbursedAmount: 27.8,
    managerName: "Huỳnh Thái Hải",
    supervisorName: "Lê Hoàng Minh",
    startDate: "2024-09-01",
    endDatePlanned: "2025-12-31",
    actualEndDate: "2025-12-20",
    currentStage: "SETTLEMENT",
    actualProgress: 98.0,
    plannedProgress: 100.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-008-1",
        updatedAt: "2026-04-15",
        updatedBy: "Huỳnh Thái Hải",
        oldProgress: 95.0,
        newProgress: 98.0,
        note: "Đã gửi hồ sơ quyết toán vốn đầu tư công sang Sở Tài chính Kiên Giang.",
      },
    ],
  },
  {
    id: "PRJ-009",
    code: "BQL-DA-2026-009",
    name: "Tuyến đường du lịch kết nối Di tích Thạch Động",
    type: "Giao thông",
    fundingSource: "Ngân sách thành phố",
    totalInvestment: 18.0,
    plan2026: 15.0,
    disbursedAmount: 0.0, // Chưa phát sinh tài chính -> được phép xóa
    managerName: "Nguyễn Văn An",
    supervisorName: "Phạm Quốc Tuấn",
    startDate: "2026-05-01",
    endDatePlanned: "2027-02-28",
    currentStage: "PREPARATION",
    actualProgress: 15.0,
    plannedProgress: 15.0,
    status: "active",
    progressHistory: [
      {
        id: "HIS-009-1",
        updatedAt: "2026-05-15",
        updatedBy: "Nguyễn Văn An",
        oldProgress: 0.0,
        newProgress: 15.0,
        note: "Đang lập hồ sơ Báo cáo nghiên cứu khả thi và lấy ý kiến quy hoạch.",
      },
    ],
  },
  {
    id: "PRJ-010",
        code: "BQL-DA-2026-010",
        name: "Nâng cấp mở rộng Bệnh viện Đa khoa TP Hà Tiên (Giai đoạn 2)",
        type: "Dân dụng",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 95.0,
        plan2026: 50.0,
        disbursedAmount: 42.5,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-05-10",
        endDatePlanned: "2026-12-15",
        currentStage: "CONSTRUCTION",
        actualProgress: 68.0,
        plannedProgress: 75.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-010-1",
            updatedAt: "2025-05-10",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 68.0,
            note: "Cập nhật tiến độ dự án Nâng cấp mở rộng Bệnh viện Đa khoa TP Hà Tiên (Giai đoạn 2).",
          },
        ],
      },
      {
        id: "PRJ-011",
        code: "BQL-DA-2026-011",
        name: "Xây dựng Trường Mầm non Pháo Đài mới đạt chuẩn quốc gia",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 22.5,
        plan2026: 18.0,
        disbursedAmount: 6.2,
        managerName: "Trần Kim Ngân",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2026-01-15",
        endDatePlanned: "2026-10-30",
        currentStage: "DESIGN",
        actualProgress: 45.0,
        plannedProgress: 45.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-011-1",
            updatedAt: "2026-01-15",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 45.0,
            note: "Cập nhật tiến độ dự án Xây dựng Trường Mầm non Pháo Đài mới đạt chuẩn quốc gia.",
          },
        ],
      },
      {
        id: "PRJ-012",
        code: "BQL-DA-2026-012",
        name: "Chiếu sáng công cộng & ngầm hóa lưới điện đường Mạc Cửu",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 34.0,
        plan2026: 25.0,
        disbursedAmount: 0.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2026-03-01",
        endDatePlanned: "2026-11-15",
        currentStage: "BIDDING",
        actualProgress: 28.0,
        plannedProgress: 30.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-012-1",
            updatedAt: "2026-03-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 28.0,
            note: "Cập nhật tiến độ dự án Chiếu sáng công cộng & ngầm hóa lưới điện đường Mạc Cửu.",
          },
        ],
      },
      {
        id: "PRJ-013",
        code: "BQL-DA-2026-013",
        name: "Nạo vét và chỉnh trang hạ lưu sông Giang Thành",
        type: "Thủy lợi",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 68.0,
        plan2026: 40.0,
        disbursedAmount: 31.0,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-07-20",
        endDatePlanned: "2026-09-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 55.0,
        plannedProgress: 60.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-013-1",
            updatedAt: "2025-07-20",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 55.0,
            note: "Cập nhật tiến độ dự án Nạo vét và chỉnh trang hạ lưu sông Giang Thành.",
          },
        ],
      },
      {
        id: "PRJ-014",
        code: "BQL-DA-2026-014",
        name: "Khu dân cư & Tái định cư phường Mỹ Đức (Khu B)",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 110.0,
        plan2026: 70.0,
        disbursedAmount: 15.0,
        managerName: "Phạm Quốc Bảo",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2026-04-01",
        endDatePlanned: "2027-06-30",
        currentStage: "PREPARATION",
        actualProgress: 20.0,
        plannedProgress: 20.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-014-1",
            updatedAt: "2026-04-01",
            updatedBy: "Phạm Quốc Bảo",
            oldProgress: 0.0,
            newProgress: 20.0,
            note: "Cập nhật tiến độ dự án Khu dân cư & Tái định cư phường Mỹ Đức (Khu B).",
          },
        ],
      },
      {
        id: "PRJ-015",
        code: "BQL-DA-2026-015",
        name: "Nâng cấp mở rộng Tỉnh lộ 28 đoạn qua đầm Đông Hồ",
        type: "Giao thông",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 145.0,
        plan2026: 90.0,
        disbursedAmount: 78.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2025-02-15",
        endDatePlanned: "2026-12-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 82.0,
        plannedProgress: 85.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-015-1",
            updatedAt: "2025-02-15",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 82.0,
            note: "Cập nhật tiến độ dự án Nâng cấp mở rộng Tỉnh lộ 28 đoạn qua đầm Đông Hồ.",
          },
        ],
      },
      {
        id: "PRJ-016",
        code: "BQL-DA-2026-016",
        name: "Xây dựng Trung tâm Văn hóa & Thể thao TP Hà Tiên",
        type: "Dân dụng",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 55.0,
        plan2026: 50.0,
        disbursedAmount: 52.0,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2024-10-01",
        endDatePlanned: "2026-06-15",
        currentStage: "INSPECTION",
        actualProgress: 96.0,
        plannedProgress: 96.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-016-1",
            updatedAt: "2024-10-01",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 96.0,
            note: "Cập nhật tiến độ dự án Xây dựng Trung tâm Văn hóa & Thể thao TP Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-017",
        code: "BQL-DA-2026-017",
        name: "Cụm hồ chứa nước ngọt và trạm bơm tăng áp xã Tiên Hải",
        type: "Thủy lợi",
        fundingSource: "Vốn ODA",
        totalInvestment: 42.0,
        plan2026: 30.0,
        disbursedAmount: 8.5,
        managerName: "Nguyễn Văn An",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2026-02-10",
        endDatePlanned: "2027-03-31",
        currentStage: "BIDDING",
        actualProgress: 32.0,
        plannedProgress: 35.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-017-1",
            updatedAt: "2026-02-10",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 32.0,
            note: "Cập nhật tiến độ dự án Cụm hồ chứa nước ngọt và trạm bơm tăng áp xã Tiên Hải.",
          },
        ],
      },
      {
        id: "PRJ-018",
        code: "BQL-DA-2026-018",
        name: "Trụ sở làm việc UBND phường Tô Châu",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 18.5,
        plan2026: 18.5,
        disbursedAmount: 18.5,
        managerName: "Trần Kim Ngân",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2024-06-01",
        endDatePlanned: "2025-11-30",
        actualEndDate: "2025-11-25",
        currentStage: "COMPLETED",
        actualProgress: 100.0,
        plannedProgress: 100.0,
        status: "closed",
        progressHistory: [
          {
            id: "HIS-018-1",
            updatedAt: "2024-06-01",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 100.0,
            note: "Cập nhật tiến độ dự án Trụ sở làm việc UBND phường Tô Châu.",
          },
        ],
      },
      {
        id: "PRJ-019",
        code: "BQL-DA-2026-019",
        name: "Đường tuần tra biên giới kết nối Cửa khẩu Quốc tế Hà Tiên",
        type: "Giao thông",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 160.0,
        plan2026: 100.0,
        disbursedAmount: 92.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-01-10",
        endDatePlanned: "2026-11-20",
        currentStage: "CONSTRUCTION",
        actualProgress: 76.0,
        plannedProgress: 80.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-019-1",
            updatedAt: "2025-01-10",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 76.0,
            note: "Cập nhật tiến độ dự án Đường tuần tra biên giới kết nối Cửa khẩu Quốc tế Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-020",
        code: "BQL-DA-2026-020",
        name: "Trạm xử lý chất thải rắn sinh hoạt liên xã phường TP Hà Tiên",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 78.0,
        plan2026: 45.0,
        disbursedAmount: 14.2,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2025-11-01",
        endDatePlanned: "2027-05-30",
        currentStage: "DESIGN",
        actualProgress: 40.0,
        plannedProgress: 50.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-020-1",
            updatedAt: "2025-11-01",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 40.0,
            note: "Cập nhật tiến độ dự án Trạm xử lý chất thải rắn sinh hoạt liên xã phường TP Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-021",
        code: "BQL-DA-2026-021",
        name: "Kè chống sạt lở kênh Vĩnh Tế (Đoạn qua TP Hà Tiên)",
        type: "Thủy lợi",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 88.0,
        plan2026: 55.0,
        disbursedAmount: 0.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2026-03-15",
        endDatePlanned: "2027-08-31",
        currentStage: "BIDDING",
        actualProgress: 30.0,
        plannedProgress: 30.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-021-1",
            updatedAt: "2026-03-15",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 30.0,
            note: "Cập nhật tiến độ dự án Kè chống sạt lở kênh Vĩnh Tế (Đoạn qua TP Hà Tiên).",
          },
        ],
      },
      {
        id: "PRJ-022",
        code: "BQL-DA-2026-022",
        name: "Công viên cây xanh sinh thái đầm Đông Hồ",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 35.0,
        plan2026: 20.0,
        disbursedAmount: 5.0,
        managerName: "Trần Kim Ngân",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2026-04-10",
        endDatePlanned: "2027-04-30",
        currentStage: "PREPARATION",
        actualProgress: 18.0,
        plannedProgress: 20.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-022-1",
            updatedAt: "2026-04-10",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 18.0,
            note: "Cập nhật tiến độ dự án Công viên cây xanh sinh thái đầm Đông Hồ.",
          },
        ],
      },
      {
        id: "PRJ-023",
        code: "BQL-DA-2026-023",
        name: "Trường THCS Thuận Yên (Khối phòng học và nhà thi đấu)",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 26.0,
        plan2026: 20.0,
        disbursedAmount: 17.5,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-08-01",
        endDatePlanned: "2026-08-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 72.0,
        plannedProgress: 75.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-023-1",
            updatedAt: "2025-08-01",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 72.0,
            note: "Cập nhật tiến độ dự án Trường THCS Thuận Yên (Khối phòng học và nhà thi đấu).",
          },
        ],
      },
      {
        id: "PRJ-024",
        code: "BQL-DA-2026-024",
        name: "Nâng cấp bến phà Hà Tiên - Phú Quốc (Cầu tàu số 2)",
        type: "Giao thông",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 72.0,
        plan2026: 65.0,
        disbursedAmount: 68.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2024-12-01",
        endDatePlanned: "2026-05-15",
        currentStage: "INSPECTION",
        actualProgress: 97.0,
        plannedProgress: 97.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-024-1",
            updatedAt: "2024-12-01",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 97.0,
            note: "Cập nhật tiến độ dự án Nâng cấp bến phà Hà Tiên - Phú Quốc (Cầu tàu số 2).",
          },
        ],
      },
      {
        id: "PRJ-025",
        code: "BQL-DA-2026-025",
        name: "Hệ thống cấp nước sạch phân phối xã Thuận Yên",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 29.0,
        plan2026: 29.0,
        disbursedAmount: 29.0,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Nguyễn Văn An",
        startDate: "2024-08-15",
        endDatePlanned: "2025-10-30",
        actualEndDate: "2025-10-28",
        currentStage: "COMPLETED",
        actualProgress: 100.0,
        plannedProgress: 100.0,
        status: "closed",
        progressHistory: [
          {
            id: "HIS-025-1",
            updatedAt: "2024-08-15",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 100.0,
            note: "Cập nhật tiến độ dự án Hệ thống cấp nước sạch phân phối xã Thuận Yên.",
          },
        ],
      },
      {
        id: "PRJ-026",
        code: "BQL-DA-2026-026",
        name: "Trạm y tế phường Đông Hồ",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 12.0,
        plan2026: 12.0,
        disbursedAmount: 11.8,
        managerName: "Trần Kim Ngân",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2024-05-01",
        endDatePlanned: "2025-08-31",
        actualEndDate: "2025-08-20",
        currentStage: "SETTLEMENT",
        actualProgress: 99.0,
        plannedProgress: 100.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-026-1",
            updatedAt: "2024-05-01",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 99.0,
            note: "Cập nhật tiến độ dự án Trạm y tế phường Đông Hồ.",
          },
        ],
      },
      {
        id: "PRJ-027",
        code: "BQL-DA-2026-027",
        name: "Tuyến đường dạo bộ và kè ven đầm Đông Hồ (Nhánh Nam)",
        type: "Giao thông",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 48.0,
        plan2026: 30.0,
        disbursedAmount: 9.6,
        managerName: "Nguyễn Văn An",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2025-12-01",
        endDatePlanned: "2027-01-31",
        currentStage: "DESIGN",
        actualProgress: 48.0,
        plannedProgress: 50.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-027-1",
            updatedAt: "2025-12-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 48.0,
            note: "Cập nhật tiến độ dự án Tuyến đường dạo bộ và kè ven đầm Đông Hồ (Nhánh Nam).",
          },
        ],
      },
      {
        id: "PRJ-028",
        code: "BQL-DA-2026-028",
        name: "Cải tạo, sửa chữa Nhà bia tưởng niệm Di tích Lịch sử Họ Mạc",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 15.0,
        plan2026: 15.0,
        disbursedAmount: 15.0,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2024-09-10",
        endDatePlanned: "2025-06-30",
        actualEndDate: "2025-06-25",
        currentStage: "COMPLETED",
        actualProgress: 100.0,
        plannedProgress: 100.0,
        status: "closed",
        progressHistory: [
          {
            id: "HIS-028-1",
            updatedAt: "2024-09-10",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 100.0,
            note: "Cập nhật tiến độ dự án Cải tạo, sửa chữa Nhà bia tưởng niệm Di tích Lịch sử Họ Mạc.",
          },
        ],
      },
      {
        id: "PRJ-029",
        code: "BQL-DA-2026-029",
        name: "Xây dựng cầu kênh Độc Nhất nối phường Pháo Đài và Tô Châu",
        type: "Giao thông",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 64.0,
        plan2026: 45.0,
        disbursedAmount: 0.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Nguyễn Văn An",
        startDate: "2026-03-20",
        endDatePlanned: "2027-09-30",
        currentStage: "BIDDING",
        actualProgress: 25.0,
        plannedProgress: 25.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-029-1",
            updatedAt: "2026-03-20",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 25.0,
            note: "Cập nhật tiến độ dự án Xây dựng cầu kênh Độc Nhất nối phường Pháo Đài và Tô Châu.",
          },
        ],
      },
      {
        id: "PRJ-030",
        code: "BQL-DA-2026-030",
        name: "Hạ tầng kỹ thuật Cụm công nghiệp Thuận Yên (Giai đoạn 1)",
        type: "Công nghiệp",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 135.0,
        plan2026: 80.0,
        disbursedAmount: 58.0,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2025-03-10",
        endDatePlanned: "2026-12-20",
        currentStage: "CONSTRUCTION",
        actualProgress: 60.0,
        plannedProgress: 65.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-030-1",
            updatedAt: "2025-03-10",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 60.0,
            note: "Cập nhật tiến độ dự án Hạ tầng kỹ thuật Cụm công nghiệp Thuận Yên (Giai đoạn 1).",
          },
        ],
      },
      {
        id: "PRJ-031",
        code: "BQL-DA-2026-031",
        name: "Kè biển bảo vệ khu neo đậu tránh trú bão Bãi Nò",
        type: "Thủy lợi",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 58.0,
        plan2026: 35.0,
        disbursedAmount: 10.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2026-02-01",
        endDatePlanned: "2027-05-15",
        currentStage: "PREPARATION",
        actualProgress: 22.0,
        plannedProgress: 25.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-031-1",
            updatedAt: "2026-02-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 22.0,
            note: "Cập nhật tiến độ dự án Kè biển bảo vệ khu neo đậu tránh trú bão Bãi Nò.",
          },
        ],
      },
      {
        id: "PRJ-032",
        code: "BQL-DA-2026-032",
        name: "Đường trục chính đô thị kết nối QL80 đi KDL Mũi Nai",
        type: "Giao thông",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 115.0,
        plan2026: 75.0,
        disbursedAmount: 62.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2025-01-05",
        endDatePlanned: "2026-10-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 70.0,
        plannedProgress: 75.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-032-1",
            updatedAt: "2025-01-05",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 70.0,
            note: "Cập nhật tiến độ dự án Đường trục chính đô thị kết nối QL80 đi KDL Mũi Nai.",
          },
        ],
      },
      {
        id: "PRJ-033",
        code: "BQL-DA-2026-033",
        name: "Trường Tiểu học Mỹ Đức 1 (Cải tạo sân bãi & nhà ăn bán trú)",
        type: "Dân dụng",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 14.0,
        plan2026: 14.0,
        disbursedAmount: 13.5,
        managerName: "Trần Kim Ngân",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2024-11-15",
        endDatePlanned: "2025-09-30",
        actualEndDate: "2025-09-20",
        currentStage: "SETTLEMENT",
        actualProgress: 99.0,
        plannedProgress: 100.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-033-1",
            updatedAt: "2024-11-15",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 99.0,
            note: "Cập nhật tiến độ dự án Trường Tiểu học Mỹ Đức 1 (Cải tạo sân bãi & nhà ăn bán trú).",
          },
        ],
      },
      {
        id: "PRJ-034",
        code: "BQL-DA-2026-034",
        name: "Trung tâm Giám sát Điều hành Đô thị Thông minh (IOC) Hà Tiên",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 25.0,
        plan2026: 25.0,
        disbursedAmount: 24.0,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-03-01",
        endDatePlanned: "2026-06-30",
        currentStage: "INSPECTION",
        actualProgress: 95.0,
        plannedProgress: 95.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-034-1",
            updatedAt: "2025-03-01",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 95.0,
            note: "Cập nhật tiến độ dự án Trung tâm Giám sát Điều hành Đô thị Thông minh (IOC) Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-035",
        code: "BQL-DA-2026-035",
        name: "Nâng cấp hệ thống thu gom và trạm bơm thoát lũ phường Tô Châu",
        type: "Thủy lợi",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 39.0,
        plan2026: 25.0,
        disbursedAmount: 7.2,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2026-01-10",
        endDatePlanned: "2027-02-28",
        currentStage: "DESIGN",
        actualProgress: 42.0,
        plannedProgress: 45.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-035-1",
            updatedAt: "2026-01-10",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 42.0,
            note: "Cập nhật tiến độ dự án Nâng cấp hệ thống thu gom và trạm bơm thoát lũ phường Tô Châu.",
          },
        ],
      },
      {
        id: "PRJ-036",
        code: "BQL-DA-2026-036",
        name: "Cải tạo chỉnh trang vỉa hè, cây xanh tuyến đường Bạch Đằng",
        type: "Giao thông",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 21.0,
        plan2026: 21.0,
        disbursedAmount: 21.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2024-07-01",
        endDatePlanned: "2025-05-30",
        actualEndDate: "2025-05-20",
        currentStage: "COMPLETED",
        actualProgress: 100.0,
        plannedProgress: 100.0,
        status: "closed",
        progressHistory: [
          {
            id: "HIS-036-1",
            updatedAt: "2024-07-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 100.0,
            note: "Cập nhật tiến độ dự án Cải tạo chỉnh trang vỉa hè, cây xanh tuyến đường Bạch Đằng.",
          },
        ],
      },
      {
        id: "PRJ-037",
        code: "BQL-DA-2026-037",
        name: "Nhà máy nước sinh hoạt đảo Hòn Heo (Quần đảo Hải Tặc)",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Vốn ODA",
        totalInvestment: 31.0,
        plan2026: 20.0,
        disbursedAmount: 0.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2026-04-15",
        endDatePlanned: "2027-07-31",
        currentStage: "BIDDING",
        actualProgress: 20.0,
        plannedProgress: 20.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-037-1",
            updatedAt: "2026-04-15",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 20.0,
            note: "Cập nhật tiến độ dự án Nhà máy nước sinh hoạt đảo Hòn Heo (Quần đảo Hải Tặc).",
          },
        ],
      },
      {
        id: "PRJ-038",
        code: "BQL-DA-2026-038",
        name: "Đường kết nối Khu du lịch Thạch Động đến Cửa khẩu Xà Xía",
        type: "Giao thông",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 82.0,
        plan2026: 55.0,
        disbursedAmount: 46.0,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-04-10",
        endDatePlanned: "2026-11-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 65.0,
        plannedProgress: 70.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-038-1",
            updatedAt: "2025-04-10",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 65.0,
            note: "Cập nhật tiến độ dự án Đường kết nối Khu du lịch Thạch Động đến Cửa khẩu Xà Xía.",
          },
        ],
      },
      {
        id: "PRJ-039",
        code: "BQL-DA-2026-039",
        name: "Trường THPT Hà Tiên (Khối phòng thực nghiệm chuyên đề)",
        type: "Dân dụng",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 33.0,
        plan2026: 25.0,
        disbursedAmount: 20.5,
        managerName: "Trần Kim Ngân",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2025-06-01",
        endDatePlanned: "2026-09-15",
        currentStage: "CONSTRUCTION",
        actualProgress: 75.0,
        plannedProgress: 78.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-039-1",
            updatedAt: "2025-06-01",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 75.0,
            note: "Cập nhật tiến độ dự án Trường THPT Hà Tiên (Khối phòng thực nghiệm chuyên đề).",
          },
        ],
      },
      {
        id: "PRJ-040",
        code: "BQL-DA-2026-040",
        name: "Cảng cá Hà Tiên (Nâng cấp luồng tàu & khu bốc dỡ hải sản)",
        type: "Thủy lợi",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 92.0,
        plan2026: 60.0,
        disbursedAmount: 18.0,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Nguyễn Văn An",
        startDate: "2026-01-20",
        endDatePlanned: "2027-10-31",
        currentStage: "PREPARATION",
        actualProgress: 26.0,
        plannedProgress: 30.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-040-1",
            updatedAt: "2026-01-20",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 26.0,
            note: "Cập nhật tiến độ dự án Cảng cá Hà Tiên (Nâng cấp luồng tàu & khu bốc dỡ hải sản).",
          },
        ],
      },
      {
        id: "PRJ-041",
        code: "BQL-DA-2026-041",
        name: "Trạm kiểm soát liên ngành Cửa khẩu Quốc tế Hà Tiên",
        type: "Dân dụng",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 46.0,
        plan2026: 30.0,
        disbursedAmount: 9.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2025-10-15",
        endDatePlanned: "2026-12-31",
        currentStage: "DESIGN",
        actualProgress: 46.0,
        plannedProgress: 50.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-041-1",
            updatedAt: "2025-10-15",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 46.0,
            note: "Cập nhật tiến độ dự án Trạm kiểm soát liên ngành Cửa khẩu Quốc tế Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-042",
        code: "BQL-DA-2026-042",
        name: "Đường gom dân sinh dọc tuyến hành lang ven biển phía Tây",
        type: "Giao thông",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 54.0,
        plan2026: 35.0,
        disbursedAmount: 0.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2026-03-01",
        endDatePlanned: "2027-04-30",
        currentStage: "BIDDING",
        actualProgress: 22.0,
        plannedProgress: 25.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-042-1",
            updatedAt: "2026-03-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 22.0,
            note: "Cập nhật tiến độ dự án Đường gom dân sinh dọc tuyến hành lang ven biển phía Tây.",
          },
        ],
      },
      {
        id: "PRJ-043",
        code: "BQL-DA-2026-043",
        name: "Hệ thống biển báo chỉ dẫn du lịch thông minh toàn TP Hà Tiên",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 9.5,
        plan2026: 9.5,
        disbursedAmount: 9.5,
        managerName: "Trần Kim Ngân",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2024-10-01",
        endDatePlanned: "2025-06-15",
        actualEndDate: "2025-06-10",
        currentStage: "COMPLETED",
        actualProgress: 100.0,
        plannedProgress: 100.0,
        status: "closed",
        progressHistory: [
          {
            id: "HIS-043-1",
            updatedAt: "2024-10-01",
            updatedBy: "Trần Kim Ngân",
            oldProgress: 0.0,
            newProgress: 100.0,
            note: "Cập nhật tiến độ dự án Hệ thống biển báo chỉ dẫn du lịch thông minh toàn TP Hà Tiên.",
          },
        ],
      },
      {
        id: "PRJ-044",
        code: "BQL-DA-2026-044",
        name: "Cải tạo hệ thống lưới điện trung hạ thế xã đảo Tiên Hải",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 28.0,
        plan2026: 28.0,
        disbursedAmount: 27.5,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2025-02-15",
        endDatePlanned: "2026-05-30",
        currentStage: "INSPECTION",
        actualProgress: 98.0,
        plannedProgress: 98.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-044-1",
            updatedAt: "2025-02-15",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 98.0,
            note: "Cập nhật tiến độ dự án Cải tạo hệ thống lưới điện trung hạ thế xã đảo Tiên Hải.",
          },
        ],
      },
      {
        id: "PRJ-045",
        code: "BQL-DA-2026-045",
        name: "Kè chống xói lở bờ biển bán đảo Mũi Nai (Giai đoạn 2)",
        type: "Thủy lợi",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 63.0,
        plan2026: 40.0,
        disbursedAmount: 28.5,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Nguyễn Văn An",
        startDate: "2025-05-01",
        endDatePlanned: "2026-11-15",
        currentStage: "CONSTRUCTION",
        actualProgress: 58.0,
        plannedProgress: 65.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-045-1",
            updatedAt: "2025-05-01",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 58.0,
            note: "Cập nhật tiến độ dự án Kè chống xói lở bờ biển bán đảo Mũi Nai (Giai đoạn 2).",
          },
        ],
      },
      {
        id: "PRJ-046",
        code: "BQL-DA-2026-046",
        name: "Đường hoa cảnh quan kết nối Chùa Hang và Hòn Phụ Tử",
        type: "Giao thông",
        fundingSource: "Ngân sách thành phố",
        totalInvestment: 37.0,
        plan2026: 25.0,
        disbursedAmount: 0.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Trần Kim Ngân",
        startDate: "2026-04-01",
        endDatePlanned: "2027-03-31",
        currentStage: "PREPARATION",
        actualProgress: 14.0,
        plannedProgress: 15.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-046-1",
            updatedAt: "2026-04-01",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 14.0,
            note: "Cập nhật tiến độ dự án Đường hoa cảnh quan kết nối Chùa Hang và Hòn Phụ Tử.",
          },
        ],
      },
      {
        id: "PRJ-047",
        code: "BQL-DA-2026-047",
        name: "Trạm cứu hỏa và bến cứu nạn thủy ven sông Giang Thành",
        type: "Dân dụng",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 24.0,
        plan2026: 18.0,
        disbursedAmount: 5.0,
        managerName: "Huỳnh Thái Hải",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2025-11-10",
        endDatePlanned: "2026-10-31",
        currentStage: "DESIGN",
        actualProgress: 44.0,
        plannedProgress: 45.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-047-1",
            updatedAt: "2025-11-10",
            updatedBy: "Huỳnh Thái Hải",
            oldProgress: 0.0,
            newProgress: 44.0,
            note: "Cập nhật tiến độ dự án Trạm cứu hỏa và bến cứu nạn thủy ven sông Giang Thành.",
          },
        ],
      },
      {
        id: "PRJ-048",
        code: "BQL-DA-2026-048",
        name: "Trụ sở Công an thành phố Hà Tiên (Khu doanh trại mới)",
        type: "Dân dụng",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 52.0,
        plan2026: 52.0,
        disbursedAmount: 50.8,
        managerName: "Phạm Quốc Tuấn",
        supervisorName: "Lê Hoàng Minh",
        startDate: "2024-07-15",
        endDatePlanned: "2025-11-30",
        actualEndDate: "2025-11-20",
        currentStage: "SETTLEMENT",
        actualProgress: 99.0,
        plannedProgress: 100.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-048-1",
            updatedAt: "2024-07-15",
            updatedBy: "Phạm Quốc Tuấn",
            oldProgress: 0.0,
            newProgress: 99.0,
            note: "Cập nhật tiến độ dự án Trụ sở Công an thành phố Hà Tiên (Khu doanh trại mới).",
          },
        ],
      },
      {
        id: "PRJ-049",
        code: "BQL-DA-2026-049",
        name: "Tuyến ống cấp nước thô từ hồ chứa nước Rạch Vược về nhà máy",
        type: "Hạ tầng kỹ thuật",
        fundingSource: "Ngân sách tỉnh",
        totalInvestment: 41.0,
        plan2026: 30.0,
        disbursedAmount: 26.0,
        managerName: "Nguyễn Văn An",
        supervisorName: "Huỳnh Thái Hải",
        startDate: "2025-03-20",
        endDatePlanned: "2026-09-30",
        currentStage: "CONSTRUCTION",
        actualProgress: 78.0,
        plannedProgress: 80.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-049-1",
            updatedAt: "2025-03-20",
            updatedBy: "Nguyễn Văn An",
            oldProgress: 0.0,
            newProgress: 78.0,
            note: "Cập nhật tiến độ dự án Tuyến ống cấp nước thô từ hồ chứa nước Rạch Vược về nhà máy.",
          },
        ],
      },
      {
        id: "PRJ-050",
        code: "BQL-DA-2026-050",
        name: "Trung tâm Triển lãm và Xúc tiến Thương mại - Du lịch Hà Tiên",
        type: "Dân dụng",
        fundingSource: "Ngân sách Trung ương",
        totalInvestment: 76.0,
        plan2026: 50.0,
        disbursedAmount: 0.0,
        managerName: "Lê Hoàng Minh",
        supervisorName: "Phạm Quốc Tuấn",
        startDate: "2026-02-15",
        endDatePlanned: "2027-08-31",
        currentStage: "BIDDING",
        actualProgress: 24.0,
        plannedProgress: 25.0,
        status: "active",
        progressHistory: [
          {
            id: "HIS-050-1",
            updatedAt: "2026-02-15",
            updatedBy: "Lê Hoàng Minh",
            oldProgress: 0.0,
            newProgress: 24.0,
            note: "Cập nhật tiến độ dự án Trung tâm Triển lãm và Xúc tiến Thương mại - Du lịch Hà Tiên.",
          },
        ],
      },
    ];
